
language: node_js
node_js:
  - "12"

stages:
  - test
  - publish

jobs:
  include:
    - stage: test
      script: npm ci && npm run lint && npm run build
      name: "tests" 
    - stage: publish
      name: "publish to npm"
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        on:
          tags: true