
language: node_js
node_js:
  - "12"

stages:
  - test
  - compile
  - name: publish
    if: branch = master

jobs:
  include:
    - stage: test
      script: npm ci && npm run lint && npm t
      name: "tests" 
    - stage: compile
      name: "build"
      script: npm ci && npm run build
    - stage: publish
      name: "publish to npm"
      script: npm ci && npm run build
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        on:
          tags: true